language: objective-c
osx_image: xcode8.3

script:
  - open -a "simulator" --args -CurrentDeviceUDID 2437D975-7A64-4F01-B8C9-2510D4DAF5AD
  - xcodebuild clean build test -project SweetRouter.xcodeproj -scheme SweetRouter -destination 'platform=iOS Simulator,OS=10.3,id=2437D975-7A64-4F01-B8C9-2510D4DAF5AD'

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: true
