language: objective-c
osx_image: xcode9

matrix:
  include:
    - script:
        - open -a "simulator" --args -CurrentDeviceUDID EEE357DD-82EF-43B5-AABC-27E3B59DB403
        - xcodebuild clean build test -project SweetRouter.xcodeproj -scheme SweetRouter -destination 'platform=iOS Simulator,OS=10.3.1,id=EEE357DD-82EF-43B5-AABC-27E3B59DB403'

    - script:
        - xcodebuild clean build test -project SweetRouter.xcodeproj -scheme SweetRouter-tvOS -destination 'platform=tvOS Simulator,OS=10.2,name=Apple TV 1080p'

    - script:
        - xcodebuild clean build test -project SweetRouter.xcodeproj -scheme SweetRouter-Mac

    - script:
        - xcodebuild clean build -project SweetRouter.xcodeproj -scheme SweetRouter-watchOS

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: true
